name = "cf-service-bindings-parent"

[site]
bucket = "./public"

[miniflare.mounts]
cf-service-bindings-child = "../child"

[[experimental_services]]
name = "CHILD"
service = "cf-service-bindings-child"
environment = "production"