name = "cf-service-bindings-child"

compatibility_date = "2022-05-11"

account_id = ""
workers_dev = true
main = "./build/index.js"

[site]
bucket = "./public"

[build]
command = "DEPLOY=true CHILD=true npm run build"

[vars]
SAMPLE_VAR = 'child service - 8'