name = "cf-service-bindings-parent"

compatibility_date = "2022-05-11"

account_id = ""
workers_dev = true
main = "./build/index.js"

[[unsafe.bindings]]
name = "CHILD"
type = "service"
service = "cf-service-bindings-child"
environment = "production"

[site]
bucket = "./public"

[build]
command = "DEPLOY=true npm run build"

[vars]
SAMPLE_VAR = 'edge service'